/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.uv.programa07cc;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tarta
 */
public class Mostrar_Productos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mostrar_Productos
     */
    DefaultTableModel dtm= new DefaultTableModel();
    DAOVenta dao=new DAOVenta();
    List<DetalleVenta> productos=new ArrayList<>();
    
    
    public Mostrar_Productos() {
        initComponents();
        initComponents();
        String [] titulo= new String[]{"ID","Cantidad","Descripcion","Precio","subtotal","IdVenta"};
        dtm.setColumnIdentifiers(titulo);
        tblReg.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Mostrar_Ventas = new javax.swing.JButton();
        Mostrar_Productos = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblReg = new javax.swing.JTable();

        setClosable(true);
        setName("Sistema de Mostrar Productos y Ventas\n"); // NOI18N

        Mostrar_Ventas.setBackground(new java.awt.Color(153, 255, 153));
        Mostrar_Ventas.setText("Mostrar Ventas");
        Mostrar_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_VentasActionPerformed(evt);
            }
        });

        Mostrar_Productos.setBackground(new java.awt.Color(153, 255, 204));
        Mostrar_Productos.setText("Mostrar Productos");
        Mostrar_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_ProductosActionPerformed(evt);
            }
        });

        tblReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblReg);

        jDesktopPane1.setLayer(Mostrar_Ventas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Mostrar_Productos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Mostrar_Ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(Mostrar_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mostrar_Ventas)
                    .addComponent(Mostrar_Productos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mostrar_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_VentasActionPerformed
        dtm= new DefaultTableModel();
        String [] titulo= new String[]{"Id Venta","Fecha","Monto"};
        dtm.setColumnIdentifiers(titulo);
        tblReg.setModel(dtm);
        List<Venta> ventas=dao.findAll();
        for (Venta venta : ventas) {
            dtm.addRow(new Object[]{
                String.valueOf(venta.getIdVenta()),String.valueOf(venta.getFecha()),String.valueOf(venta.getMonto())
            });
        }
    }//GEN-LAST:event_Mostrar_VentasActionPerformed

    private void Mostrar_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_ProductosActionPerformed
        // TODO add your handling code here:
        dtm= new DefaultTableModel();
        String [] titulo= new String[]{"ID","Cantidad","Descripcion","Precio","subtotal","IdVenta"};
        dtm.setColumnIdentifiers(titulo);
        tblReg.setModel(dtm);
        List<Venta> ventas=dao.findAll();
        for (Venta venta : ventas) {
            for (DetalleVenta p : venta.getDetalle()) {
                dtm.addRow(new Object[]{
                    String.valueOf(p.getIdProducto()),String.valueOf(p.getCantidad()),String.valueOf(p.getDescripcion()),String.valueOf(p.getPrecio()),String.valueOf(p.getSubtotal()),String.valueOf(venta.getIdVenta())
                });
            }
        }
    }//GEN-LAST:event_Mostrar_ProductosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mostrar_Productos;
    private javax.swing.JButton Mostrar_Ventas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblReg;
    // End of variables declaration//GEN-END:variables
}
