/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.uv.programa07cc;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ProductoGUI extends javax.swing.JInternalFrame {
    DefaultTableModel dtm= new DefaultTableModel();
    DAOVenta dao=new DAOVenta();
    List<DetalleVenta> productos=new ArrayList<>();
    /**
     * Creates new form VentaProductoGUI
     */
    public ProductoGUI() {
        initComponents();
        String [] titulo= new String[]{"ID","Cantidad","Descripcion","Precio","subtotal","IdVenta"};
        dtm.setColumnIdentifiers(titulo);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBrVenta = new javax.swing.JButton();
        btnAgrVenta = new javax.swing.JButton();
        Descripcion_Producto = new javax.swing.JTextField();
        Cantidad_producto = new javax.swing.JTextField();
        Precio_Producto = new javax.swing.JTextField();
        btnAgrProd = new javax.swing.JButton();
        IdVenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setTitle("Tiendita de chimichangas");

        jLabel1.setText("Id Venta: ");

        btnBrVenta.setBackground(new java.awt.Color(255, 0, 0));
        btnBrVenta.setText("Borrar Venta");
        btnBrVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrVentaActionPerformed(evt);
            }
        });

        btnAgrVenta.setBackground(new java.awt.Color(153, 255, 204));
        btnAgrVenta.setText("Agregar Venta");
        btnAgrVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrVentaActionPerformed(evt);
            }
        });

        Precio_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_ProductoActionPerformed(evt);
            }
        });

        btnAgrProd.setBackground(new java.awt.Color(153, 255, 153));
        btnAgrProd.setText("Agregar Producto");
        btnAgrProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrProdActionPerformed(evt);
            }
        });

        IdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdVentaActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripcion: ");

        jLabel3.setText("Cantidad: ");

        jLabel4.setText("Precio: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Precio_Producto)
                                .addComponent(Cantidad_producto)
                                .addComponent(Descripcion_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgrProd, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgrVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Descripcion_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cantidad_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Precio_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgrProd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgrVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnBrVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrVentaActionPerformed
        if(IdVenta.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "***Ingrese la id de la venta***");
        }
        else{
            int id= Integer.parseInt(IdVenta.getText());
            boolean res=dao.delete(id);
            if(res){
                JOptionPane.showMessageDialog(null, "La venta ha sido borrada");
                this.IdVenta.setText("");
                this.Cantidad_producto.setText("");
                this.Descripcion_Producto.setText("");
                this.Precio_Producto.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null, "No existe la venta");
            }
        }
    }//GEN-LAST:event_btnBrVentaActionPerformed

    private void btnAgrVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrVentaActionPerformed
        Venta vent;
        Date fecha= Date.from(Instant.now());
        if(productos.isEmpty()){
            JOptionPane.showMessageDialog(null, "Productos de ventas no existentes");
        }
        else{
            vent = new Venta();
            vent.setFecha(new java.sql.Date(fecha.getTime()));
            double monto = 0;
            for (DetalleVenta producto : productos) {
                producto.setVenta(vent);
                monto = monto + producto.getSubtotal();
                vent.getDetalle().add(producto);
            }
            vent.setMonto(monto);
            if (dao.create(vent) != null) {
                if (dtm.getRowCount() > 0) {
                    for (int i = dtm.getRowCount() - 1; i > -1; i--) {
                        dtm.removeRow(i);
                    }
                }
                JOptionPane.showMessageDialog(null, "Agregada exitósamente");
                this.Cantidad_producto.setText("");
                this.Descripcion_Producto.setText("");
                this.Precio_Producto.setText("");
                for (DetalleVenta p : vent.getDetalle()) {
                    dtm.addRow(new Object[]{
                        String.valueOf(p.getIdProducto()), String.valueOf(p.getCantidad()), String.valueOf(p.getDescripcion()), String.valueOf(p.getPrecio()), String.valueOf(p.getSubtotal()), String.valueOf(vent.getIdVenta())
                    });
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar");
            }
        }
    }//GEN-LAST:event_btnAgrVentaActionPerformed

    private void btnAgrProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrProdActionPerformed
        if(Cantidad_producto.getText().isEmpty()||Descripcion_Producto.getText().isEmpty()||Precio_Producto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "***Un campo está vacío***");
        }
        else{
            if (dtm.getRowCount() > 0) {
                for (int i = dtm.getRowCount() - 1; i > -1; i--) {
                    dtm.removeRow(i);
                }
            }
            dtm = new DefaultTableModel();
            String[] titulo = new String[]{"ID", "Cantidad", "Descripcion", "Precio", "subtotal", "IdVenta"};
            dtm.setColumnIdentifiers(titulo);            
            double cant = Double.parseDouble(Cantidad_producto.getText());
            double prec= Double.parseDouble(Precio_Producto.getText());
            double subtotal=cant*prec;
            DetalleVenta det= new DetalleVenta();
            det.setCantidad(cant);
            det.setDescripcion(Descripcion_Producto.getText());
            det.setPrecio(prec);
            det.setSubtotal(subtotal);
            dtm.addRow(new Object[]{"",Cantidad_producto.getText(),Descripcion_Producto.getText(),Precio_Producto.getText(),String.valueOf(subtotal),""});
            productos.add(det);
            this.Cantidad_producto.setText("");
            this.Descripcion_Producto.setText("");
            this.Precio_Producto.setText("");
        }

    }//GEN-LAST:event_btnAgrProdActionPerformed

    private void Precio_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_ProductoActionPerformed

    private void IdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cantidad_producto;
    private javax.swing.JTextField Descripcion_Producto;
    private javax.swing.JTextField IdVenta;
    private javax.swing.JTextField Precio_Producto;
    private javax.swing.JButton btnAgrProd;
    private javax.swing.JButton btnAgrVenta;
    private javax.swing.JButton btnBrVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
